---
image: python:latest

ansible:lint:
  before_script:
    - pip install --root-user-action=ignore ansible
    - pip install --root-user-action=ignore ansible-dev-tools
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install ansible.posix
  script:
    - ansible-lint archall.yml
