---
image: python:latest

# enum(.pre, build, test, deploy, .post)
stages:
  - test

linting-job:
  stage: test
  before_script:
    - pip install ansible-dev-tools
  script:
    - ansible-lint archall.yml
