---
image: python:latest

# enum(.pre, build, test, deploy, .post)
stages:
  - .pre
  - test

ansible:setup:
  stage: .pre
  script:
    - pip install --root-user-action=ignore ansible
    - pip install --root-user-action=ignore ansible-dev-tools
    - pip show ansible
  after_script:
    - echo "$PATH"
    - echo "$PWD"
    - ansible-lint --version
    - which ansible

ansible:collection-install:
  stage: .pre
  needs: ["ansible:setup"]
  before_script:
    - echo $PATH
  script:
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install ansible.posix

lint-code:
  stage: test
  needs: ["ansible:setup", "ansible:collection-install"]
  script:
    - ansible-lint archall.yml
    
