---
- name: Install language runtimes and compilers.
  ansible.builtin.package:
    name:
      - go
      - nodejs
    state: latest # noqa: package-latest

- name: Install development essentials.
  ansible.builtin.package:
    name:
      - git
      - git-filter-repo
      - gitsign
      - cosign
      - ruff
      - uv
    state: latest # noqa: package-latest

- name: Install other development utilities.
  ansible.builtin.package:
    name:
      - toolbox
    state: latest # noqa: package-latest

- name: Install virtualisation tools.
  ansible.builtin.package:
    name:
      - libvirt
      - libvirt-python
      - virt-install
      - virt-manager
      - qemu-base
      - qemu-system-x86
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-guest-utils
      - virtualbox-host-modules-arch
    state: latest # noqa: package-latest

# slirp4ns and fuse-overlayfs are needed for rootless podman
# To set subuid / subgid for user namespaces inside container:
# sudo usermod --add-subuids 100000-165535 \
#              --add-subgids 100000-165535 <username>
- name: Install containerisation tools.
  ansible.builtin.package:
    name:
      - podman
      - podman-compose
      - buildah
      - skopeo
      - conmon
      - containers-common
      - fuse-overlayfs
      - slirp4netns
      - netavark
    state: latest # noqa: package-latest

- name: Install infrastructure automation tools.
  ansible.builtin.package:
    name:
      - opentofu
      - terraform
    state: latest # noqa: package-latest

- name: Install terragrunt terraform wrapper.
  ansible.builtin.package:
    name:
      - terragrunt
    state: latest # noqa: package-latest
  tags: [never, terragrunt]

- name: Install nix package manager.
  ansible.builtin.package:
    name:
      - nix
    state: latest # noqa: package-latest
  notify: enable nix daemon

- name: Configure nix experimental features.
  ansible.builtin.lineinfile:
    dest: /etc/nix/nix.conf
    regexp: "^(#)?extra-experimental-features"
    line: "extra-experimental-features = flakes command"
    state: present
    # validate: 'TBD'
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: restart nix daemon
