---
- name: Install language runtimes and compilers.
  ansible.builtin.package:
    name:
      - go
      - nodejs
    state: latest # noqa: package-latest

- name: Install development essentials.
  ansible.builtin.package:
    name:
      - git
      - git-filter-repo
      - gitsign
      - cosign
      - ruff
      - uv
    state: latest # noqa: package-latest

- name: Install other development utilities.
  ansible.builtin.package:
    name:
      - toolbox
    state: latest # noqa: package-latest

- name: Install virtualisation tools.
  ansible.builtin.package:
    name:
      - libvirt
      - libvirt-python
      - virt-install
      - virt-manager
      - qemu-base
      - qemu-system-x86
      - qemu-desktop
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-guest-utils
      - virtualbox-host-modules-arch
    state: latest # noqa: package-latest

# slirp4ns and fuse-overlayfs are needed for rootless podman
# To set subuid / subgid for user namespaces inside container:
# sudo usermod --add-subuids 100000-165535 \
#              --add-subgids 100000-165535 <username>
- name: Install containerisation tools.
  ansible.builtin.package:
    name:
      - podman
      - podman-compose
      - buildah
      - skopeo
      - conmon
      - containers-common
      - fuse-overlayfs
      - slirp4netns
      - netavark
    state: latest # noqa: package-latest

- name: Install infrastructure automation tools.
  ansible.builtin.package:
    name:
      - opentofu
      - terraform
    state: latest # noqa: package-latest

- name: Install terragrunt terraform wrapper.
  ansible.builtin.package:
    name:
      - terragrunt
    state: latest # noqa: package-latest
  tags: [never, terragrunt]

- name: Install Kubernetes client tools.
  ansible.builtin.package:
    name:
      - kubectl
      - helm
    state: latest # noqa: package-latest

- name: Install nix package manager.
  ansible.builtin.package:
    name:
      - nix
    state: latest # noqa: package-latest
  notify: enable nix daemon

- name: Configure nix experimental features.
  ansible.builtin.lineinfile:
    dest: /etc/nix/nix.conf
    regexp: "^(#)?extra-experimental-features"
    line: "extra-experimental-features = flakes nix-command"
    state: present
    # validate: 'TBD'
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: restart nix daemon

- name: Configure git signing (sub)key.
  community.general.git_config:
    name: user.signingkey
    value: "BE025865EB94267F!"
    scope: global
    state: present

- name: Configure git tag signing.
  community.general.git_config:
    name: tag.gpgsign
    value: true
    scope: global
    state: present

- name: Configure git commit signing.
  community.general.git_config:
    name: commit.gpgsign
    value: true
    scope: global
    state: present

- name: Configure git default editor.
  community.general.git_config:
    name: core.editor
    value: vim
    scope: global
    state: present

- name: Configure git aliases.
  community.general.git_config:
    name: alias.{{ item.alias }}
    value: "{{ item.value }}"
    scope: global
    state: present
  with_items:
    - alias: aliases
      value: config --get-regexp '^alias\.'
    - alias: br
      value: branch
    - alias: co
      value: checkout
    - alias: cm
      value: commit
    - alias: diffc
      value: diff --cached
    - alias: st
      value: status
    - alias: lg
      value: log --oneline --graph --all
